// Options for select taken from Rails: http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html
export default [
  { name: 'International Date Line West', value: 'Pacific/Midway' },
  { name: 'Midway Island', value: 'Pacific/Midway' },
  { name: 'American Samoa', value: 'Pacific/Pago_Pago' },
  { name: 'Hawaii', value: 'Pacific/Honolulu' },
  { name: 'Alaska', value: 'America/Juneau' },
  { name: 'Pacific Time (US & Canada)', value: 'America/Los_Angeles' },
  { name: 'Tijuana', value: 'America/Tijuana' },
  { name: 'Mountain Time (US & Canada)', value: 'America/Denver' },
  { name: 'Arizona', value: 'America/Phoenix' },
  { name: 'Chihuahua', value: 'America/Chihuahua' },
  { name: 'Mazatlan', value: 'America/Mazatlan' },
  { name: 'Central Time (US & Canada)', value: 'America/Chicago' },
  { name: 'Saskatchewan', value: 'America/Regina' },
  { name: 'Guadalajara', value: 'America/Mexico_City' },
  { name: 'Mexico City', value: 'America/Mexico_City' },
  { name: 'Monterrey', value: 'America/Monterrey' },
  { name: 'Central America', value: 'America/Guatemala' },
  { name: 'Eastern Time (US & Canada)', value: 'America/New_York' },
  { name: 'Indiana (East)', value: 'America/Indiana/Indianapolis' },
  { name: 'Bogota', value: 'America/Bogota' },
  { name: 'Lima', value: 'America/Lima' },
  { name: 'Quito', value: 'America/Lima' },
  { name: 'Atlantic Time (Canada)', value: 'America/Halifax' },
  { name: 'Caracas', value: 'America/Caracas' },
  { name: 'La Paz', value: 'America/La_Paz' },
  { name: 'Santiago', value: 'America/Santiago' },
  { name: 'Newfoundland', value: 'America/St_Johns' },
  { name: 'Brasilia', value: 'America/Sao_Paulo' },
  { name: 'Buenos Aires', value: 'America/Argentina/Buenos_Aires' },
  { name: 'Montevideo', value: 'America/Montevideo' },
  { name: 'Georgetown', value: 'America/Guyana' },
  { name: 'Greenland', value: 'America/Godthab' },
  { name: 'Mid-Atlantic', value: 'Atlantic/South_Georgia' },
  { name: 'Azores', value: 'Atlantic/Azores' },
  { name: 'Cape Verde Is.', value: 'Atlantic/Cape_Verde' },
  { name: 'Dublin', value: 'Europe/Dublin' },
  { name: 'Edinburgh', value: 'Europe/London' },
  { name: 'Lisbon', value: 'Europe/Lisbon' },
  { name: 'London', value: 'Europe/London' },
  { name: 'Casablanca', value: 'Africa/Casablanca' },
  { name: 'Monrovia', value: 'Africa/Monrovia' },
  { name: 'UTC', value: 'Etc/UTC' },
  { name: 'Belgrade', value: 'Europe/Belgrade' },
  { name: 'Bratislava', value: 'Europe/Bratislava' },
  { name: 'Budapest', value: 'Europe/Budapest' },
  { name: 'Ljubljana', value: 'Europe/Ljubljana' },
  { name: 'Prague', value: 'Europe/Prague' },
  { name: 'Sarajevo', value: 'Europe/Sarajevo' },
  { name: 'Skopje', value: 'Europe/Skopje' },
  { name: 'Warsaw', value: 'Europe/Warsaw' },
  { name: 'Zagreb', value: 'Europe/Zagreb' },
  { name: 'Brussels', value: 'Europe/Brussels' },
  { name: 'Copenhagen', value: 'Europe/Copenhagen' },
  { name: 'Madrid', value: 'Europe/Madrid' },
  { name: 'Paris', value: 'Europe/Paris' },
  { name: 'Amsterdam', value: 'Europe/Amsterdam' },
  { name: 'Berlin', value: 'Europe/Berlin' },
  { name: 'Bern', value: 'Europe/Zurich' },
  { name: 'Zurich', value: 'Europe/Zurich' },
  { name: 'Rome', value: 'Europe/Rome' },
  { name: 'Stockholm', value: 'Europe/Stockholm' },
  { name: 'Vienna', value: 'Europe/Vienna' },
  { name: 'West Central Africa', value: 'Africa/Algiers' },
  { name: 'Bucharest', value: 'Europe/Bucharest' },
  { name: 'Cairo', value: 'Africa/Cairo' },
  { name: 'Helsinki', value: 'Europe/Helsinki' },
  { name: 'Kyiv', value: 'Europe/Kiev' },
  { name: 'Riga', value: 'Europe/Riga' },
  { name: 'Sofia', value: 'Europe/Sofia' },
  { name: 'Tallinn', value: 'Europe/Tallinn' },
  { name: 'Vilnius', value: 'Europe/Vilnius' },
  { name: 'Athens', value: 'Europe/Athens' },
  { name: 'Istanbul', value: 'Europe/Istanbul' },
  { name: 'Minsk', value: 'Europe/Minsk' },
  { name: 'Jerusalem', value: 'Asia/Jerusalem' },
  { name: 'Harare', value: 'Africa/Harare' },
  { name: 'Pretoria', value: 'Africa/Johannesburg' },
  { name: 'Kaliningrad', value: 'Europe/Kaliningrad' },
  { name: 'Moscow', value: 'Europe/Moscow' },
  { name: 'St. Petersburg', value: 'Europe/Moscow' },
  { name: 'Volgograd', value: 'Europe/Volgograd' },
  { name: 'Samara', value: 'Europe/Samara' },
  { name: 'Kuwait', value: 'Asia/Kuwait' },
  { name: 'Riyadh', value: 'Asia/Riyadh' },
  { name: 'Nairobi', value: 'Africa/Nairobi' },
  { name: 'Baghdad', value: 'Asia/Baghdad' },
  { name: 'Tehran', value: 'Asia/Tehran' },
  { name: 'Abu Dhabi', value: 'Asia/Muscat' },
  { name: 'Muscat', value: 'Asia/Muscat' },
  { name: 'Baku', value: 'Asia/Baku' },
  { name: 'Tbilisi', value: 'Asia/Tbilisi' },
  { name: 'Yerevan', value: 'Asia/Yerevan' },
  { name: 'Kabul', value: 'Asia/Kabul' },
  { name: 'Ekaterinburg', value: 'Asia/Yekaterinburg' },
  { name: 'Islamabad', value: 'Asia/Karachi' },
  { name: 'Karachi', value: 'Asia/Karachi' },
  { name: 'Tashkent', value: 'Asia/Tashkent' },
  { name: 'Chennai', value: 'Asia/Kolkata' },
  { name: 'Kolkata', value: 'Asia/Kolkata' },
  { name: 'Mumbai', value: 'Asia/Kolkata' },
  { name: 'New Delhi', value: 'Asia/Kolkata' },
  { name: 'Kathmandu', value: 'Asia/Kathmandu' },
  { name: 'Astana', value: 'Asia/Dhaka' },
  { name: 'Dhaka', value: 'Asia/Dhaka' },
  { name: 'Sri Jayawardenepura', value: 'Asia/Colombo' },
  { name: 'Almaty', value: 'Asia/Almaty' },
  { name: 'Novosibirsk', value: 'Asia/Novosibirsk' },
  { name: 'Rangoon', value: 'Asia/Rangoon' },
  { name: 'Bangkok', value: 'Asia/Bangkok' },
  { name: 'Hanoi', value: 'Asia/Bangkok' },
  { name: 'Jakarta', value: 'Asia/Jakarta' },
  { name: 'Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
  { name: 'Beijing', value: 'Asia/Shanghai' },
  { name: 'Chongqing', value: 'Asia/Chongqing' },
  { name: 'Hong Kong', value: 'Asia/Hong_Kong' },
  { name: 'Urumqi', value: 'Asia/Urumqi' },
  { name: 'Kuala Lumpur', value: 'Asia/Kuala_Lumpur' },
  { name: 'Singapore', value: 'Asia/Singapore' },
  { name: 'Taipei', value: 'Asia/Taipei' },
  { name: 'Perth', value: 'Australia/Perth' },
  { name: 'Irkutsk', value: 'Asia/Irkutsk' },
  { name: 'Ulaanbaatar', value: 'Asia/Ulaanbaatar' },
  { name: 'Seoul', value: 'Asia/Seoul' },
  { name: 'Osaka', value: 'Asia/Tokyo' },
  { name: 'Sapporo', value: 'Asia/Tokyo' },
  { name: 'Tokyo', value: 'Asia/Tokyo' },
  { name: 'Yakutsk', value: 'Asia/Yakutsk' },
  { name: 'Darwin', value: 'Australia/Darwin' },
  { name: 'Adelaide', value: 'Australia/Adelaide' },
  { name: 'Canberra', value: 'Australia/Melbourne' },
  { name: 'Melbourne', value: 'Australia/Melbourne' },
  { name: 'Sydney', value: 'Australia/Sydney' },
  { name: 'Brisbane', value: 'Australia/Brisbane' },
  { name: 'Hobart', value: 'Australia/Hobart' },
  { name: 'Vladivostok', value: 'Asia/Vladivostok' },
  { name: 'Guam', value: 'Pacific/Guam' },
  { name: 'Port Moresby', value: 'Pacific/Port_Moresby' },
  { name: 'Magadan', value: 'Asia/Magadan' },
  { name: 'Srednekolymsk', value: 'Asia/Srednekolymsk' },
  { name: 'Solomon Is.', value: 'Pacific/Guadalcanal' },
  { name: 'New Caledonia', value: 'Pacific/Noumea' },
  { name: 'Fiji', value: 'Pacific/Fiji' },
  { name: 'Kamchatka', value: 'Asia/Kamchatka' },
  { name: 'Marshall Is.', value: 'Pacific/Majuro' },
  { name: 'Auckland', value: 'Pacific/Auckland' },
  { name: 'Wellington', value: 'Pacific/Auckland' },
  { name: 'Nuku\'alofa', value: 'Pacific/Tongatapu' },
  { name: 'Tokelau Is.', value: 'Pacific/Fakaofo' },
  { name: 'Chatham Is.', value: 'Pacific/Chatham' },
  { name: 'Samoa', value: 'Pacific/Apia' }
];
