#!/usr/bin/env ruby

# run a command 
def runCmd(cmd)
	puts cmd
	puts
	output = `#{cmd}`
	# was the command a success?
	unless $?.success?
		printErrors output
		exit(false)
	end
	return output
end

def printErrors(text)
  puts "\n--ERRORS--\n"
  currentFile = ""
  lines = text.split("\n")
  lines.each do |line|
    line = line.chomp()
    unless line.empty?
      if line.start_with? "/"
        currentFile = line
        currentFilePrinted = false
      end
      if line.include? "error "
        unless currentFilePrinted   
          puts "\n"
          puts currentFile
          currentFilePrinted = true
        end
        puts line
      end
    end
  end
  puts "\n\n"
end
		
# get the current branch
current_branch = runCmd('git branch --show-current').chomp()

# switch to the production branch
runCmd("git checkout master")

# pull the new production code
runCmd("git pull")

# update yarn, in case the yarn.lock file changed
runCmd("yarn")

# run the tests
runCmd("yarn lint:js")
runCmd("yarn test:ember")

# perform the deploy

# what is the command for a production deploy?
cmd = "node_modules/.bin/ember deploy production --verbose"
runCmd(cmd)

# switch back to the "current"
runCmd("git checkout #{current_branch}")

