#!/usr/bin/env ruby

# run a command 
def runCmd(cmd)
	puts cmd
	puts
	output = `#{cmd}`
	# was the command a success?
	unless $?.success?
		puts output
		puts	
		puts "FAILED"
		exit(false)
	end
	return output
end
		
# get the current branch
current_branch = runCmd('git branch --show-current').chomp()

# switch to the staging branch
runCmd("git checkout staging")

# pull the new staging code
runCmd("git pull")

# update yarn, in case the yarn.lock file changed
runCmd("yarn")

# run the tests
runCmd("yarn lint:js")
runCmd("yarn test:ember")

# perform the deploy

# what is the command for a staging deploy?
cmd = "TARGET=staging node_modules/.bin/ember deploy production --verbose"
runCmd(cmd)

# switch back to the "current"
runCmd("git checkout #{current_branch}")

